// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package sqlc

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID       int64
	ParentID sql.NullInt64
	EventID  int64
	UserID   int64
	Comment  string
	PostedAt time.Time
}

type Event struct {
	ID     int64
	Title  string
	Start  time.Time
	Place  string
	Open   time.Time
	Close  time.Time
	Author int64
}

type EventsUser struct {
	ID        int64
	EventID   int64
	UserID    int64
	Cancelled bool
}

type Upload struct {
	ID      int64
	EventID int64
	Url     string
}

type User struct {
	ID   int64
	Uid  string
	Name string
}
