// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package sqlc

import (
	"time"
)

type Comment struct {
	ID       int64
	Eventid  int64
	Userid   int64
	Comment  string
	Postedat time.Time
}

type Event struct {
	ID     int64
	Title  string
	Start  time.Time
	Place  string
	Open   time.Time
	Close  time.Time
	Author int64
}

type Eventuser struct {
	ID      int64
	Eventid int64
	Userid  int64
	Status  int32
}

type Upload struct {
	ID      int64
	Eventid int64
	Url     string
}

type User struct {
	ID   int64
	Uid  string
	Name string
}
