version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventsite
      MYSQL_USER: eventsite
      MYSQL_PASSWORD: eventsite
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: eventsite
    build: .
    ports:
      - 8081:8081
    volumes:
      - .:/app

  api:
    image: eventsite
    build: .
    container_name: api
    ports:
      - 8082:8082
    volumes:
      - .:/app
    command: air -c /app/.air_api.toml

  pocketbase:
    image: pocketbase:local
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    container_name: pocketbase
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./pb_data:/app/pb_data
    ports:
      - 8090:8090
