openapi: '3.0.2'
info:
  title: eventsite
  version: '1.0'
servers:
  - url: http://localhost:8082/v1
paths:
  /events:
    get:
      tags:
        - events
      summary: Get all events.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'

components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        start:
          type: string
          format: date-time
        place:
          type: string
        open:
          type: string
          format: date-time
        close:
          type: string
          format: date-time
        author:
          type: integer
          format: int64

