import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import EventList from '../components/event-list'

const EventListPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href="/">Top</a>
      <EventList></EventList>
    </div>
  )
}

export default EventListPage
