import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import EventForm from '../components/event-form'

const EventCreate: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href="/">Top</a>
      <EventForm></EventForm>
    </div>
  )
}

export default EventCreate
