/*
 * eventsite
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	"github.com/umemak/eventsite_go/openapi"
)

func main() {
	log.Printf("Server started")

	EventsApiService := openapi.NewEventsApiService()
	EventsApiController := openapi.NewEventsApiController(EventsApiService)

	router := openapi.NewRouter(EventsApiController)

	log.Fatal(http.ListenAndServe(":8082", router))
}
