openapi: 3.0.2
info:
  title: eventsite
  version: "1.0"
servers:
- url: https://localhost:8082/v1
paths:
  /events:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Event'
                type: array
          description: OK
      summary: Get all events.
      tags:
      - events
components:
  schemas:
    Event:
      example:
        author: 6
        start: 2000-01-23T04:56:07.000+00:00
        id: 0
        place: place
        title: title
        close: 2000-01-23T04:56:07.000+00:00
        open: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          format: int64
          type: integer
        title:
          type: string
        start:
          format: date-time
          type: string
        place:
          type: string
        open:
          format: date-time
          type: string
        close:
          format: date-time
          type: string
        author:
          format: int64
          type: integer
      type: object
